<?php

$routes = [
    // Rutas principales
    '/' => 'HomeController@index',
    '/home' => 'HomeController@index',
    '/dashboard' => 'DashboardController@index',
    '/login' => 'HomeController@login',
    '/logout' => 'HomeController@logout',
    '/pattern-recovery' => 'HomeController@patternRecovery',
    '/reset' => 'HomeController@resetPassword',
    '/productos/listar' => 'ProductoController@listar',
    '/categorias/listar' => 'CategoriaController@listar',
    '/categorias/guardar' => 'CategoriaController@guardar',
    '/categorias/actualizar' => 'CategoriaController@actualizar',
    '/categorias/eliminar' => 'CategoriaController@eliminar',
    '/proveedores/listar' => 'ProveedorController@listar',
    '/proveedores/guardar' => 'ProveedorController@guardar',
    '/proveedores/actualizar' => 'ProveedorController@actualizar',
    '/proveedores/eliminar' => 'ProveedorController@eliminar',
    '/clientes/listar' => 'ClienteController@listar',
    '/clientes/guardar' => 'ClienteController@guardar',
    '/clientes/actualizar' => 'ClienteController@actualizar',
    '/clientes/eliminar' => 'ClienteController@eliminar',
    '/usuarios/listar' => 'UsuarioController@listar',
    '/usuarios/guardar' => 'UsuarioController@guardar',
    '/usuarios/actualizar' => 'UsuarioController@actualizar',
    '/usuarios/listarActivo' => 'UsuarioController@listarActivo',
    '/usuarios/eliminar' => 'UsuarioController@eliminar',
    '/perfil/actualizarDatos' => 'UsuarioController@actualizarDatos',
    '/perfil/actualizarCredenciales' => 'UsuarioController@actualizarCredenciales',
    '/perfil/actualizarPatron' => 'UsuarioController@actualizarPatron',
    '/entradas/registrar' => 'MovimientoController@registrarEntrada',
    '/salidas/registrar' => 'MovimientoController@registrarSalida',
    '/movimientos/listar' => 'MovimientoController@listar',
];
