<?php

$routes = [
    // Rutas principales
    '/' => 'HomeController@index',
    '/home' => 'HomeController@index',
    '/dashboard' => 'DashboardController@index',
    '/login' => 'HomeController@login',
    '/logout' => 'HomeController@logout',
    '/reset' => 'HomeController@resetPassword',
    '/solicitar-recuperacion' => 'HomeController@solicitarRecuperacion',
    '/recuperar-contrasena' => 'HomeController@mostrarFormularioRecuperacion',
    '/restablecer-password' => 'HomeController@restablecerPassword',
    '/productos/listar' => 'ProductoController@listar',
    '/categorias/listar' => 'CategoriaController@listar',
    '/categorias/guardar' => 'CategoriaController@guardar',
    '/categorias/actualizar' => 'CategoriaController@actualizar',
    '/categorias/eliminar' => 'CategoriaController@eliminar',
    '/proveedores/listar' => 'ProveedorController@listar',
    '/proveedores/guardar' => 'ProveedorController@guardar',
    '/proveedores/actualizar' => 'ProveedorController@actualizar',
    '/proveedores/eliminar' => 'ProveedorController@eliminar',
    '/clientes/listar' => 'ClienteController@listar',
    '/clientes/guardar' => 'ClienteController@guardar',
    '/clientes/actualizar' => 'ClienteController@actualizar',
    '/clientes/eliminar' => 'ClienteController@eliminar',
    '/usuarios/listar' => 'UsuarioController@listar',
    '/usuarios/guardar' => 'UsuarioController@guardar',
    '/usuarios/actualizar' => 'UsuarioController@actualizar',
    '/usuarios/listarActivo' => 'UsuarioController@listarActivo',
    '/usuarios/eliminar' => 'UsuarioController@eliminar',
    '/entradas/registrar' => 'MovimientoController@registrarEntrada',
    '/salidas/registrar' => 'MovimientoController@registrarSalida',
    '/movimientos/listar' => 'MovimientoController@listar',
];
